config:
  global:
    resolve_timeout: 5m
  route:
    group_by: ['alertname', 'cluster', 'service']
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 4h
    receiver: 'slack-notifications'
  receivers:
  - name: 'slack-notifications'
    slack_configs:
    - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
      channel: '#alerts'
      send_resolved: true
      title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
      text: >-
        {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Status:* {{ .Status }}
          *Started:* {{ .StartsAt }}
          {{ if .EndsAt }}*Ended:* {{ .EndsAt }}{{ end }}
        {{ end }}
      color: {{ if eq .Status "firing" }}danger{{ else }}good{{ end }}
      footer: 'Atrade Alerting'
      actions:
      - type: button
        text: 'View in Grafana'
        url: '{{ .Annotations.grafana_url }}'
        style: '{{ if eq .Status "firing" }}danger{{ else }}default{{ end }}'

persistentVolume:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce 