apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: atrade-alerts
  namespace: atrade
spec:
  groups:
  - name: atrade
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High error rate detected
        description: Error rate is above 10% for the last 5 minutes
        grafana_url: "http://grafana:3000/d/atrade-dashboard"

    - alert: HighLatency
      expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High latency detected
        description: Average response time is above 1 second for the last 5 minutes
        grafana_url: "http://grafana:3000/d/atrade-dashboard"

    - alert: HighMemoryUsage
      expr: container_memory_usage_bytes{container="atrade-app"} > 400Mi
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage detected
        description: Container memory usage is above 400MB for the last 5 minutes
        grafana_url: "http://grafana:3000/d/atrade-dashboard"

    - alert: DatabaseConnectionIssues
      expr: pg_up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Database connection issues
        description: Cannot connect to the database
        grafana_url: "http://grafana:3000/d/atrade-dashboard"

    - alert: RedisConnectionIssues
      expr: redis_up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Redis connection issues
        description: Cannot connect to Redis
        grafana_url: "http://grafana:3000/d/atrade-dashboard" 