apiVersion: v1
kind: ConfigMap
metadata:
  name: atrade-config
  namespace: atrade
data:
  DATABASE_URL: "postgresql://postgres:$(DB_PASSWORD)@atrade-db:5432/trading_system"
  REDIS_URL: "redis://atrade-redis:6379/0"
  DEBUG: "0"
  LOG_LEVEL: "INFO"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  MAX_WORKERS: "4"
  WORKER_TIMEOUT: "120"
  CORS_ORIGINS: "https://atrade.example.com"
  ALLOWED_HOSTS: "atrade.example.com"
  SSL_ENABLED: "true"
  SSL_CERT_PATH: "/etc/nginx/ssl/cert.pem"
  SSL_KEY_PATH: "/etc/nginx/ssl/key.pem"
  TRADING_INITIAL_CAPITAL: "100000"
  TRADING_MAX_POSITION_SIZE: "10000"
  RISK_MAX_DRAWDOWN: "0.1"
  RISK_LEVERAGE: "1.0"
  RISK_CORRELATION: "0.7" 