apiVersion: v1
kind: PersistentVolume
metadata:
  name: atrade-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/atrade
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: atrade-logs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/atrade/logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: atrade-db-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/atrade/db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: atrade-redis-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/atrade/redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atrade-data-pvc
  namespace: atrade
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atrade-logs-pvc
  namespace: atrade
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atrade-db-pvc
  namespace: atrade
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atrade-redis-pvc
  namespace: atrade
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 