apiVersion: v1
kind: Secret
metadata:
  name: atrade-secrets
  namespace: atrade
type: Opaque
data:
  # Base64 encoded values
  DB_PASSWORD: cG9zdGdyZXM=  # postgres
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQta2V5  # your-super-secret-key
  ALPHA_VANTAGE_API_KEY: eW91ci1hbHBoYS12YW50YWdlLWtleQ==  # your-alpha-vantage-key
  POLYGON_API_KEY: eW91ci1wb2x5Z29uLWtleQ==  # your-polygon-key 