database:
  host: localhost
  port: 5432
  name: trading_system
  user: postgres
  password: postgres

api:
  host: 0.0.0.0
  port: 8000
  debug: false

trading:
  initial_capital: 100000.0
  max_position_size: 0.1
  stop_loss_pct: 0.02
  take_profit_pct: 0.05

risk:
  max_drawdown: 0.1
  max_leverage: 2.0
  max_correlation: 0.7

logging:
  level: INFO
  file: logs/trading_system.log

redis:
  host: localhost
  port: 6379
  db: 0

security:
  jwt_secret_key: your-secret-key-here
  jwt_algorithm: HS256
  access_token_expire_minutes: 30

external_api:
  alpha_vantage_api_key: your-api-key-here
  polygon_api_key: your-api-key-here 